version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "tokushimaru_portal.local:127.0.0.1"
      - "sm.tokushimaru_portal.local:127.0.0.1"
      - "sp.tokushimaru_portal.local:127.0.0.1"
      - "sp_entry.tokushimaru_portal.local:127.0.0.1"

  db:
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql